DROP TABLE IF EXISTS example1;
DROP TABLE IF EXISTS example2;
DROP TABLE IF EXISTS example3;

CREATE TABLE example1 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    data1 TEXT NOT NULL, 
    data2 TEXT NOT NULL,
    data3 REAL NOT NULL
);

CREATE TABLE example2 (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    date REAL NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE example3 (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    name TEXT NOT NULL,
    phone INTEGER NOT NULL
);